Add support for AWS ECR and GCP scopes

diff --git a/bin/awsl b/bin/awsl
--- a/bin/awsl
+++ b/bin/awsl
@@ -1,26 +1,38 @@
 #!/bin/bash
 name="$(basename $0)"
-usage="${name} [-h] profile"
+usage="${name} [-h] [-e] -p profile"
 description="Log in to an AWS named profile."
 options="
-  -h, --help  show help
-  profile     the profile to use"
+  -h          show help
+  -e          log in Docker to ECR
+  -p profile  the profile to use"
 
 # Processing command-line arguments
 emph="\e[1;34m"
 reset="\e[0m"
-if [[ $# != 1 ]]; then
-    echo "${name}: error: invalid arguments"
-    echo "usage: ${usage}"
-    exit 1
-fi
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+
+_help() {
     echo -e "${emph}Usage:${reset} ${usage}\n"
     echo -e "${description}\n"
     echo -e "${emph}Options:${reset}${options}"
     exit
-fi
-profile="$1"
+}
+
+_arg_error() {
+    echo "${name}: error: $1"
+    echo "usage: ${usage}"
+    exit 1
+}
+
+while getopts 'hep:' flag; do
+    case "${flag}" in
+        h) _help ;;
+        e) ecr=true ;;
+        p) profile="${OPTARG}" ;;
+        *) _arg_error 'invalid arguments' ;;
+    esac
+done
+if [[ -z "${profile}" ]]; then _arg_error 'missing profile'; fi
 
 # Logging in
 echo 'Executing "aws sso login"...'
@@ -61,3 +73,13 @@ aws configure --profile "${profile}" set aws_secret_access_key \
     "$(echo "${credentials}" | jq .secretAccessKey -r)"
 aws configure --profile "${profile}" set aws_session_token \
     "$(echo "${credentials}" | jq .sessionToken -r)"
+
+# Logging in to ECR
+if [[ -n "${ecr}" ]]; then
+    for registry in 'public.ecr.aws' "${account_id}.dkr.ecr.${region}.amazonaws.com"; do
+        if [[ "${registry}" == public* ]]; then subcommand='ecr-public'; else subcommand='ecr'; fi
+        echo -e "Authenticating Docker CLI to ${registry}"
+        aws "${subcommand}" get-login-password --region "${region}" --profile="${profile}" | \
+            docker login --username AWS --password-stdin "${registry}"
+    done
+fi
